### ISSUE TITLE
PortalSocket Disconnected!

### ISSUE THREAD

**Issue by mainlove** [seven1240/FreeSWITCH-Portal#2]
WebSocket connection to 'ws://192.168.147.129:8080/socket' failed: Error during WebSocket handshake: Unexpected response code: 401

不能建立websocket连接  ，  是需要其他mod的配置，还是要额外的设置

用的是chrome

**Comment by seven1240** [comment]
配置xml_rpc.conf.xml，打开 enable-websocket

**Comment by mainlove** [comment]
OK 大概是版本老了点
 默认xml_rpc.conf.xml里面没有   enable-websocket的提示
加入
    param name="enable-websocket" value="true"
即可
